- .github/workflows/upload_pypi.yml
Removed Python version matrix and used Py3.6 instead.
> Removed Python version matrix

- CHANGELOG.md
Update changelog for the v0.0.2 release.
> CHANGELOG.md: add changes for v0.0.2

- .readthedocs.yml
Add config file for installing required packages to build documentation.
> add readthedocs config

- doc/user/installation.rst
- doc/user/quickstart.rst
This PR adds some documentation via sphinx which largely covers the quickstart and installation section of `README.md`.
> update quickstart/installation in docs based on README.md

- dev-requirements.txt
- requirements.txt
> Add requirements

- CHANGELOG.md
This PR updates the changelog and ensures that the build passes. Upon merging, we should be able to tag the corresponding commit and trigger the release pipeline.
> bump version to 0.0.4

- CHANGELOG.md
This PR updates the changelog to prepare the v0.0.5 release.
See #65.
> Release: v0.0.5

- tests/test_version.py
Adding a small fix for version test to have better coverage
> enhancing version test

- CHANGELOG.md
Update changelog, prepare for release. See #105.
> hop-client version 0.2

- tests/test_auth.py
Nothing fancy; these tests just exercise more of the branches in `auth.load_auth`. 
* ~[ ] `make doc` runs without errors and generated docs render correctly.~
> Add more auth tests to improve coverage

- tests/test_auth.py
Code run in a child process evades detection in the coverage reporting.
This change should get us that last little bit of coverage on hop/configure.py. The code also turns out to be a little simpler, as a bonus. 
* ~[ ] `make doc` runs without errors and generated docs render correctly.~
> Prefer script_runner to subprocess.Popen

- doc/conf.py
- hop/io.py
- tests/test_io.py
This only adds documentation for existing features
> Add documentation of optional parameters which are passed down to lower level Kafka libraries

- CHANGELOG.md
See https://github.com/scimma/hop-client/issues/129.
> hop-client v0.3.0

- CHANGELOG.md
See https://github.com/scimma/hop-client/issues/135.
N/A
> hop-client v0.4.0 release

- doc/conf.py
This PR adds relevant changes needed to support the newest major version of Sphinx (4.x).
Closes #143.
> Documentation: Sphinx 4.x compatibility

- hop/io.py
- hop/list_topics.py
- tests/test_io.py
This is placed in `io` since there didn't seem to be an obviously better place. 
This addition addresses issue #148 . 
> Make topic listing part of the API

- CHANGELOG.md
> Release v0.5.1

- hop/io.py
- setup.py
- tests/test_auth.py
- tests/test_cli.py
- tests/test_io.py
This change exposes the timeout option, as requested in https://github.com/scimma/hop-client/issues/184 .
> Expose the timeout option for listing topics

- hop/io.py
- tests/test_io.py
This is useful for archiving messages, avoiding the overhead of deserialization when they should be stored serialized, anyway.
> Allow messages to be consumed without deserialization

- CHANGELOG.md
https://github.com/scimma/hop-client/issues/207
> Tag v0.9.0

- CHANGELOG.md
Release version v0.10.1
Release issue: https://github.com/scimma/hop-client/issues/217
> Release version v0.10.1

- doc/user/models.rst
- hop/models.py
- tests/conftest.py
- tests/data/expected_data/example_avro.stdout
- tests/test_models.py
This is an updated and completed version of #190 from @cmessick.
> Allow AvroBlob to take either a single record or a list of records

- hop/auth.py
Fixes https://github.com/scimma/hop-client/issues/221 by skipping writing certifi CA paths which are trivially recovered when reading the auth data.
> Avoid writing ceretifi paths to the auth store

- .github/workflows/upload_package.yml
- CHANGELOG.md
https://github.com/scimma/hop-client/issues/226
> Release v0.11.0

- CHANGELOG.md
Release PR for https://github.com/scimma/hop-client/issues/236
> Release v0.11.1

- hop/subscribe.py
This mirrors the `kcat` `-D` option, and the default value of a newline character makes output more readable. 
> Add a user-configurable delimiter between messages

- CHANGELOG.md
Implement https://github.com/scimma/hop-client/issues/246
> Release version v0.12.0
