MANIFEST.in, README.md, tests/data/example.gcn3
This PR adds an example GCN circular, `example.gcn3` in `tests/data`, adds the relevant files to the manifest, and documents its use in the README.
=> Add example GCN circular

Makefile
This PR adds a target in the `Makefile`, `make changelog`, to update the version in there automatically based on the current version reported by the scimma client.
The way I intend for this tool to be used is as part of the release process, in which one would update the changelog based on the proposed version (e.g. `make changelog VERSION=0.0.4`), create a commit with something like "bump version to 0.0.4" and open up a PR to ensure all the relevant tests pass and get reviewed. After that is done, we can then create a tag on that commit and push the tags to start the release pipeline.
This process works if we update the changelog in the `[Unreleased]` section for any relevant changes as PRs get opened up (example in #39), which also has a nice paper trail associated with it.
=> auto-changelog version updates

Makefile, setup.cfg
See title. Also modify `setup.cfg` to ignore the version file when linting, plus tabs->spaces.
=> Add `make format` to show any code change recommendations

doc/api/api.rst, doc/api/io.rst, doc/api/models.rst, doc/index.rst, doc/user/quickstart.rst, doc/user/stream.rst, scimma/client/__init__.py, scimma/client/io.py, scimma/client/models.py, scimma/client/publish.py, setup.py, tests/conftest.py, tests/test_cli.py, tests/test_io.py, tests/test_publish.py
This PR implements #48, to define a python-based client API to read and write messages from a Kafka broker. The way it's done is to have a small wrapper around the genesis client, allowing us to implement different defaults and further down the line, control which messages are allowed without expecting the genesis client to do so.
In doing so, I have also implemented data classes for GCN Circulars and VOEvents to define the structure of messages, which are used within `scimma publish` for the circulars.
Additionally, there has been some restructuring in the test suite to avoid repeating code.
This can merged independently of #5, and the test suite restructure may help out there as well.
One example:
```
from scimma.client import stream
with stream.open("kafka://hostname:port/topic", "r", …
```
=> Expose a python-based client API

scimma/client/models.py, setup.cfg, setup.py, tests/conftest.py
Adds a new class method in the `VOEvent` model to read in XML formatted VOEvents, either from a file object, string, or generator.
Example:
```
from scimma.client import models
with open("voevent.xml", "rb") as f:
voevent = models.VOEvent.from_xml(f)
```
=> Add VOEvent.from_xml()

README.md, doc/user/quickstart.rst, scimma/client/publish.py, setup.py, tests/conftest.py, tests/test_cli.py, tests/test_models.py
This PR implements #43, to be able to publish GCN notices from VOEvent files in XML format. In doing this, I had put some thought into how the command line interface was going to look like as we allow more types of messages to be published (and subscribed from) without cluttering the API and hopefully making it a bit intuitive to use.
Here's what I came up with:
```
scimma publish kafka://hostname:port/notice example1.xml example2.xml
```
I thought a reasonable thing to do was to make the parsing based on the file extension until we have proper schema validation. VOEvents (which notices are formatted in commonly) reasonably expect to be in XML format and circulars stored on the NASA GCN website have the .gcn3 extension.
I also changed the broker URL to be a positional argument, since it's …
=> Publish GCN Notices from VOEvent-formatted files

scimma/client/subscribe.py
An update to the Genesis streaming client removed message index from the return output of
a scimma-client Stream object. This was overlooked in the primary subscriber PR #55, which was developed using an older version of ADC/Genesis. This hotfix removes the reference to the now-absent index.
See related Genesis commit here:
https://github.com/astronomy-commons/genesis-client/commit/39f3458faf002d6a0511e4e0af9c61fb3c05c1c3
=> Fix usage of io.Stream.open to reflect changes in Genesis

.github/workflows/upload_package.yml, recipe/meta.yaml
This PR implements fixes to the build variables and dependencies in the conda recipe.
This PR also addresses #61, namely by separating the upload to PyPI from the upload to Conda. This allows a developer to [properly trigger](https://github.com/scimma/hop-client/actions/runs/75451315) the upload workflow without [failures](https://github.com/scimma/hop-client/runs/534766612?check_suite_focus=true) due to hash/URL mismatching. This fix removes the need for hash-checking and on-the-fly recipe editing by specifying the source URL using `git_url` and `git_tag` instead of PyPI.
=> Fix upload workflow variables/dependencies and PyPI/Conda upload

hop/__init__.py
This PR modifies `__init__.py` to declare `hop` as a namespace, which allows the `hop.apps` namespace to work correctly when installed via `python setup.py install`, or possibly other installation methods.
=> Declare `hop` as a namespace for downstream apps

Makefile, doc/conf.py, hop/models.py, setup.cfg, setup.py, tests/test_cli.py, tests/test_models.py
This PR accomplishes a few tasks, mostly related to dev tooling and enumerated below:
* Update Makefile with targets from `adc-streaming`. The main thing I wanted here is the use of `autopep8` rather than `black` for code formatting, which is a bit less aggressive in its formatting and more configurable.
* Revert some of the aggressive formatting done by black in a few modules.
* Run linter/formatter to catch a few items to fix.
* Remove a print statement which was used for testing.
* Update dev extras requirement for using `autopep8`.
* Also added a `zip_safe = False` flag from adc-streaming, which tends to discourage making python eggs. Seems like a good option all around.
=> Update dev tooling from adc-streaming

recipe/meta.yaml, setup.py
adc-streaming has released an incompatible v1.0.0. We can't use it yet. A future revision will use the new API.
Just pin the version specified in setup.py and the conda recipe.
=> Pin version of adc-streaming

README.md, doc/user/quickstart.rst, hop/auth.py, recipe/meta.yaml, setup.py, tests/conftest.py, tests/test_auth.py
This PR switches the configuration format from librdkafka-style conf to TOML, based on #85. In addition, the `Auth` class in `auth.py` has been modified to expose `SCRAM-SHA-512` as the default SASL mechanism. Finally, upon setup to generate a new configuration file, the user is prompted for a username and password (using `getpass.getpass()` to hide the password).
=> Switch auth configuration to TOML

README.md, doc/user/auth.rst, doc/user/quickstart.rst, doc/user/stream.rst, hop/io.py, hop/publish.py, hop/subscribe.py, tests/test_io.py
This PR provides a more consistent experience between the CLI and python API. For example, for the CLI, auth credentials were automatically loaded in from a configuration file, but one needs to explicitly pass in an `Auth` instance for the python API. This change in behavior for the two interfaces has been removed. Now, the same defaults are present in both, and a `Stream()` instance by default uses authentication.
@spenczar, while I was doing this, I was thinking about the conversation from a previous PR (https://github.com/scimma/hop-client/pull/82#discussion_r447181113) on why options can be passed in both the `Stream` constructor and for `Stream.open()`. I'm rethinking my original position and leaning towards "ya ain't gonna need it" and instead just giving the default `Stream` …
=> Consistency between CLI and python API

CHANGELOG.md, recipe/meta.yaml, setup.py
This PR updates the changelog and minimum version of adc-streaming to 1.0.2. See #93 for the release checklist.
=> hop-client 0.1 release

hop/publish.py, tests/test_cli.py
This PR implements https://github.com/scimma/hop-client/issues/86, to pipe messages into `hop publish`. This allows things like:
```
cat stringlist.txt | hop publish kafka://host:port/topic
```
and also
```
hop publish kafka://host:port/topic < stringlist.txt
```
A few gotchas about this is that you need to be careful to not add keyword arguments between positional arguments, since argparse will get confused and try to process one of those keyword arguments as a message.
Another is this likely won't make sense to use for circulars due to the format of said messages. We should probably add a sanity check that disables this message format when trying to parse messages from stdin.
Finally, I don't have a good way of adding in test coverage for this, since emulating terminal input seems to be …
=> Piping input into hop publish

doc/user/stream.rst, hop/io.py, hop/utils/cli.py, tests/conftest.py, tests/test_io.py
Basically, the big thing here is a rework of the internal Producer/Consumer classes used within `stream.open()`.
These features can be split into allowing manual committing of messages, changing the API slightly for clarity, and making it easier to hold long-lived references to an open stream.
1. Manual committing of messages is done by calling `mark_done()` on an open stream in read mode. To do this, you can commit the optional metadata when finished processing a message. This is similar to what's being done in adc-streaming, but since it uses confluent-kafka's `Message` type to commit messages, instead it'll hold a reference to this `Message` in an internal attributre in the `Metadata` produced that can be returned when using the Consumer..
2. One pattern I've seen within different …
=> Expose manual committing of messages + allow use of stream.open() without context manager

hop/io.py, hop/models.py, tests/conftest.py, tests/test_io.py
This PR changes the behavior of unstructured (Blob) messages when they're unpacked to return the message content rather than a Blob class to be a bit more intuitive, first noted by @shereenElSayed. To clarify, if you try to publish unstructured messages and subscribe to them, you'll get back a Blob rather than the message you originally sent which can be a bit confusing.
This also updates the tests to reflect the change and makes a few changes within the Blob class. Removed the comment about the reason for adding the Blob in the docstring, updated the type annotation for the content attribute to reflect any JSON-serializable content, and updated the `load()` method to update the content tag rather than unpacking the content into the blob (if it worked before, it is by coincidence).
NOTE: …
=> Return message content rather than Blob when unpacking messages

hop/auth.py, tests/test_auth.py, tests/test_cli.py
Perform auth tests in temporary directories to avoid state leaking in
from the user's home directory. Fine-tune the version requirement to
avoid the mock_file.read() bug.
Fixes #108
=> Improve test reliability

hop/__main__.py, tests/test_cli.py
Introduce a 'debug' option to show full error stack traces.
Internal stack traces are generally not useful to end users. This patch reduces error messages, by default, down to a more traditional unix error format, i.e. `hop: error message`, but includes an option to get the full output for debugging.
=> Show short error messages to users by default

hop/io.py, tests/test_io.py
This avoids failing with an error of "'NoneType' object is not iterable" which doesn't explain the actual problem to the user.
This should help inform users who are unfamiliar with Kafka that they must specify a topic, although helping them find the topic they want is a separate, larger problem. 
=> Provide a clear error when no topic is specified

Makefile
This prevents the test, format, and lint targets from analyzing
unversioned files which are present in the same directory, like
packages installed in a virtualenv.
This might be a matter of taste, but I find it handy to have the working copy be the same directory as a virtualenv, but without this change flake8 takes in excess of 20 CPU minutes as it struggles to process the half million lines of dependencies. 
=> Target specific files and directories in make rules

tests/test_configure.py
The coverage checker still complains about hop/configure:94-98, although that code is really part of the CLI and is already exercised by that set of tests. However, if it would be preferable to convince the coverage tool, I can add some direct tests for `configure._main` as well. 
* ~[ ] `make doc` runs without errors and generated docs render correctly.~
=> Add tests for the main functions in hop.configure

codecov.yml
This PR attempts to modify the codecov configuration so that codecov posts code coverage on PRs more consistently as well as changing some of the conditions for displaying warnings, errors based on how much the coverage changes from the current coverage.
~~* [ ] All new functions and classes are documented and adhere to Google doc style (3.8.3-3.8.6 of [this](http://google.github.io/styleguide/pyguide.html#383-functions-and-methods) document)~~
~~* [ ] Add/update sphinx documentation with any relevant changes.~~
~~* [ ] Add/update pytest-style tests in `/tests`, ensuring sufficient code coverage.~~
~~* [ ] `make test` runs without errors.~~
~~* [ ] `make lint` doesn't give any warnings.~~
~~* [ ] `make format` doesn't give any code formatting suggestions.~~
~~* [ ] `make doc` runs without …
=> Modify codecov configuration

hop/models.py, tests/test_models.py
This includes the tweak to MessageModel.load to tell anyone who does call it directly not to do so. 
=> Increase test coverage for the models

doc/user/commands.rst, hop/publish.py, tests/conftest.py, tests/test_cli.py, tests/test_io.py
This allows data output from `hop subscribe` to be fed back into
`hop publish`. It is a breaking change, so users of this interface,
if any exist, should be considered.
Aside from the interface change, which consists of a single additional call to `json.loads`, most of this patch rewrites the mock_broker and surrounding test code in order to test the new feature. I was unable to get the old approach using a combination of `MagicMock` and `functools.partialmethod` to do anything sensible (all writes kept vanishing into thin air), but it's possible I just made some mistake, and if so I would be happy to refactor this patch. 
* ~[ ] All new functions and classes are documented and adhere to Google doc style (3.8.3-3.8.6 of [this](http://google.github.io/styleguide/pyguide.html#383-functions-a …
=> Change the publish CLI to treat input from stdin as JSON.

hop/auth.py, hop/configure.py, tests/conftest.py, tests/test_auth.py, tests/test_configure.py, tests/test_io.py
Closes #124
Refuse to open config files which have over-broad permissions (and prompt the user to fix them). Also, produce config files with safe permissions by default. 
=> Require that credential files have private permissions

hop/auth.py, hop/io.py, tests/test_auth.py, tests/test_io.py
When using proper authentication, prefix the group name with the credential username, instead of the local username. When a username is not available, simply use a purely random group name.
It would be cleaner to just not use a consumer group unless requested by the user, which other Kafka tools appear to support, but confluent kafka does not permit this.
=> Change how consumer group names are generated

doc/user/quickstart.rst, hop/__main__.py, hop/list_topics.py, tests/test_cli.py
This adds a subcommand which will either list all of the accessible topics, or list the subset of requested topics which exist and are accessible.
=> Add a CLI subcommand to list topics

hop/__main__.py, hop/auth.py, tests/test_auth.py, tests/test_cli.py
Additionally, refactor errors from `auth.load_auth` for better context.
When running without a subcommand, as users are likely to do right after installation, detect if there is no configuration or it is not valid, and give some advice on how to proceed. 
=> Give directions when the user has no configuration set up.

doc/user/stream.rst, hop/auth.py, hop/configure.py, hop/io.py, hop/list_topics.py, hop/subscribe.py, tests/conftest.py, tests/test_auth.py, tests/test_cli.py, tests/test_configure.py, tests/test_io.py
Two features are removed, due to incompatibility with this one:
- Consumer group IDs can no longer be specified as part of a broker URL, as the userinfo is used as a credential username.
- Multiple brokers cannot be specified in a single URL, as this creates ambiguity in selecting credentials by hostname.
Writing configuration files in the new format and providing a user interface for managing them will be implemented subsequently.
=> Change the internal representation to handle multiple credentials.

doc/user/quickstart.rst, doc/user/stream.rst, hop/io.py, hop/subscribe.py, tests/test_cli.py, tests/test_io.py
This changes the default behavior within the client so that listening to messages indefinitely is the default. See #145. The flag used to control this behavior was changed from `persist/--persist` to `until_eos/--until-eos`. Setting `until_eos=True/--until-eos` will only read messages until an end of stream (EOS) is received.
=> Stream: Change default to listen to messages indefinitely (until_eos=False)

hop/auth.py, tests/test_cli.py
Fixes https://github.com/scimma/hop-client/issues/153
=> Add the missing force option to `hop auth add`

hop/__main__.py, hop/auth.py, hop/cli.py, hop/configure.py, hop/io.py, hop/publish.py, hop/subscribe.py, tests/test_cli.py, tests/test_configure.py
Implements #146. Added some logging functionality in the cli module and shared throughout our CLI commands. By default, INFO-level logs are displayed and routed to stderr to allow piping/redirects to continue working. This can be changed with `--quiet` which only shows warnings/errors or `--verbose` which also shows DEBUG-level logs as well.
A couple of other changes unrelated to this but was caught when adding in logging include:
* Organize imports in `auth` module. I had to add an import and saw it wasn't organized like some of the other modules.
* Remove default signal handler in `__main__.py`. This was causing issues with KeyboardInterrupts and prematurely exiting the program without closing the producer/consumer instances. Instead, this case is handled explicitly now.
* In a similar …
=> UX: Improve logging in CLI when publishing/subscribing

setup.py
This should avoid issues with the upcoming major release of adc-streaming once it's available in PyPI with the current released version of hop-client. The working plan I had in mind for releases are:
* 0.4.1 release of hop-client with this pinning in place.
* 2.0 release of adc-streaming.
* 0.5.0 release of hop-client with newest changes (and #155) pinned with adc-streaming >= 2.0.
=> Pin adc-streaming to 1.x

README.md, dev-requirements.txt, requirements.txt
These files aren't used and are outdated. The authoritative set of dependencies/versions is baked into `setup.py` and having these around are confusing at best.
=> Remove outdated requirements files

doc/api/api.rst, doc/api/robust_publisher.rst, doc/index.rst, doc/user/robust_publication.rst, hop/robust_publisher.py, tests/test_rpub.py
This patch is not entirely complete and ready to merge, but I would like to begin reviewing it for reasons discussed below. All naming and organization should be up for discussion; I wasn't sure where we would want things so I have put them in a new file and given them 'strawman' names. Since we may want to change some or all of this, the usage documentation is not yet written; obviously that must be done before the review and merge complete. 
As a specific, more minor issue, the linter is not happy with `hop.robust_publisher.PublicationJournal._read_previous_journal`. The 
method is indeed fairly long, but most of my ideas for splitting it up would add more conceptual complexity, as state that currently exists shared within it would have to be shared among multiple methods. Suggestions …
=> Implementation of robust publication

hop/auth.py, tests/conftest.py, tests/test_auth.py
Add OAUTHBEARER / OpenID Connect (OIDC) support as described in [KIP-768]. This is the authentication mechanism used by the GCN/TACH Kafka broker.
Depends on astronomy-commons/adc-streaming#53.
=> Add OAUTHBEARER/OIDC support

doc/user/commands.rst, hop/publish.py, tests/test_cli.py
After the major format refactoring, the CLI tool was continuing to accept only JSON when reading from standard input, while simultaneously enforcing that the `BLOB` format had to be requested. This was inconsistent and unhelpful. This patch separates the two formats, allowing either to be specified, and uses the standard `MessageModel.load` interface to interpet the message data (so JSON is parsed as such, and Blob data is left alone). 
Relax requirement that input may not be from a TTY.
=> Cli format cleanup

setup.py
pytest was pinned at <= 5.3 in commit 8268ac0, though I'm not sure of the reason. pytest 6.2.5 and above appear to work properly, with all tests passing on python 3.6.1 and 3.9.15 on my machine.
pytest 6.2.5 fixed python 3.10 compatibility
https://docs.pytest.org/en/stable/changelog.html#pytest-6-2-5-2021-08-29
=> Use pytest>=6.2.5 for Python 3.10 compatibility

hop/io.py, tests/test_io.py
Currently, reading a message that has binary data without the proper deserialize plugin throws a UnicodeDecodeError exception.
I think the expected behavior is to create a Blob with the bytes.
This PR ignores any UnicodeDecodeErrors alongside JSONDecodeErrors
=> Create Blob instead of crashing on binary data on deserialize

hop/auth.py, setup.py, tests/test_auth.py
- Hostname URI checks were overly strict previously, and would reject literal IPv6 addresses for containing colons. 
- URIs with a default port explicitly specified were not matched against it being left implicit, or vice-versa, which defeated much of the purpose of allowing the port specification to be optional.
~* [ ] Add/update sphinx documentation with any relevant changes.~
=> Support IPv6 literal addresses and handle default ports sensibly

hop/robust_publisher.py, tests/test_rpub.py
RobustPublisher currently does not work at all because it's using an older auth API. It isn't caught in the tests because `Stream` gets mocked like the old format. This PR fixes it using the credential selection code from `Stream.open`.
=> Fix authentication procedure in RobustPublisher

hop/io.py
This change just exposes the existing functionality in librdkafka/adc-streaming to commit consumer group offsets sychronously, rather than the default of asynchronous commit. 
~* [ ] Add/update pytest-style tests in `/tests`, ensuring sufficient code coverage.~
=> Expose ability to commit offsets synchronously

hop/io.py, setup.py, tests/test_io.py
Exposes the stop method for the underlying adc-streaming Consumer class.
=> Expose stop method for Consumer

hop/models.py, tests/conftest.py, tests/test_io.py, tests/test_models.py
A question for review: The code currently assumes that the notices will be UTF-8. Is this correct?
=> Add a message model for text GCN notices

doc/user/stream.rst, hop/io.py, setup.py, tests/conftest.py, tests/test_io.py
Based on https://github.com/astronomy-commons/adc-streaming/pull/69 , this exposes the same functionality through the hop API.
=> Expose the capability to multiple topics

.github/workflows/build.yml, doc/index.rst, doc/user/commands.rst, hop/configure.py, hop/http_scram.py, hop/io.py, hop/models.py, hop/publish.py, hop/robust_publisher.py, setup.py, tests/conftest.py, tests/data/expected_data/example_blob.stdout, tests/test_auth.py, tests/test_cli.py, tests/test_configure.py, tests/test_http_scram.py, tests/test_io.py, tests/test_models.py, tests/test_rpub.py
This set of commits adds the integration with the archive API (or any other compatible implementation) to offload messages which are too large to directly transmit through a Kafka topic. 
It also includes an implementation of configuration parameters for users who might want to turn this off, which involves putting in some general machinery for configuration which we didn't really have before.
Known potential issues and things which are not completely implemented:
1. If a (publishing) client checks a topic's message size limit, but the topic then has its size limit decreased, and the client tries to send a message whose size is between the old and new size limits before performing its next periodic settings check, the send will fail instead of being offloaded. Handling this case is not …
=> Implement Large Message Offloading

doc/user/large_messages.rst, hop/io.py, tests/test_io.py
This provides users with a work-around for https://github.com/scimma/hop-client/issues/234
=> Completely avoid making metadata queries to brokers when automatic_offload is set to false

hop/models.py, tests/conftest.py, tests/test_io.py, tests/test_models.py
This fixes the long-standing annoyance that the VOEvent model could not output data in its original format, or indeed in the format that it could itself load. 
Messages previously serialized to JSON can be restored to XML with the loss of some metadata attributes.
This is a breaking change in that messages serialized by this updated version will not be readable by old versions. 
=> Change VOEvent storage and serialization to preserve the original XML.

Makefile, doc/user/stream.rst, hop/io.py, hop/publish.py, pyproject.toml, tests/conftest.py, tests/test_cli.py, tests/test_io.py
- Support a timeout for io.Producer.flush and close, and use produce_timeout as the default
- Expose the timeout as a parameter for the CLI publish command
This fixes, or enables the user to work around, the obnoxious failure modes of publishing, particularly of `hop publish`, to exit before all messages have been transmitted to the broker. 
Depends on [adc-streaming commit f710c8889c9656cb420f9ec66162be21127efb68](https://github.com/astronomy-commons/adc-streaming/pull/73)
=> Improve handling of high message volumes

.coveragerc, README.md, hop/bson/LICENSE, hop/bson/LICENSE_APACHE, hop/bson/__init__.py, hop/bson/codec.py, hop/bson/network.py, hop/bson/objectid.py, hop/bson/py3compat.py, hop/bson/tz_util.py, hop/io.py, pyproject.toml, tests/test_io.py
This attempts to fix https://github.com/scimma/hop-client/issues/248 while keeping large message offload support working by default. 
=> Attempt to vendor the stand-alone bson package to prevent conflicts with pymongo
